timeslice:
  detector_eff: 1.0
  n_stations: 35
  r_min: 150
  r_max: 850
  max_tracks: 6
  mean_events: 15
dataset:
  dataset_name: TrackML
  name_of_directory: ML_15Event/ML_SN2
  n_samples: 1000
  test_fraction: 0.3
model:
  encoder:
    hidden_linear_layers:
    - 128
    - 128
    - 64
    out_linear_layer: 32
    n_convolutions: 6
  classifier:
    edge_weight_layers:
    - 128
    - 128
    edge_update_layers:
    - 128
    - 128
    node_update_layers:
    - 128
    - 128
    n_convolutions: 6
  super_graph:
    neighborhood_degree: 2
    hand_filter: 1
training:
  pos_weight: 1
  neg_weight: 0.6
  gamma: 1.5
  save_prob: 1
  n_epochs: 110
visualization:
  plot_label: ML_SN2
loader:
  load_model: true
  model_dirrectory: ML_10Event/ML_Test5
  model_name: ML_Test5_model_epoch_400
saver:
  model_name: ML_SN2_model
  save_step: 10
device:
  node: 0
