

timeslice:
  max_tracks: 6
  mean_events: 15
  time_resolution: 5

detector:
  detector_eff: 0.95
  n_stations: 35
  r_min: 75
  r_max: 850


dataset:
  dataset_name: "SPD"
  MLtrackPath: ""
  name_of_directory: "TestDir_ForEval"
  n_samples: 100
  test_fraction: 1



Log_parms:
  log_label: LogName

loader:
  model_dirrectory: "C:/Users/suka1/NN/GNN_practice/TrackGANN/SPD_15Event/SPD_DeltaT5"
  model_name: "SPD_DeltaT5_model_epoch_420"


model:
  encoder:
    hidden_linear_layers:
    - 128
    - 128
    - 64
    out_linear_layer: 32
    n_convolutions: 4
  classifier:
    edge_weight_layers:
    - 128
    - 128
    edge_update_layers:
    - 128
    - 128
    node_update_layers:
    - 128
    - 128
    n_convolutions: 4



