
name_of_directory: TrainDir

detector:
  detector_eff: 0.95
  n_stations: 15
  r_min: 150
  r_max: 850

Train_dataset:
  dataset_name: SPD
  MLtrackPath: ""
  dataset_directory: Train
  time_resolution: 5
  max_tracks: 6
  mean_events: 15
  n_samples: 800


Test_dataset:
  dataset_name: SPD
  MLtrackPath: ""
  dataset_directory: TestSPD
  time_resolution: 5
  max_tracks: 6
  mean_events: 15
  n_samples: 300
  log_label: SPD15_DeltaT5
  

Test_dataset1:
  dataset_name: TrackML
  MLtrackPath: path_to_the_directory_containing_the_folders_"trainN"_from_TrackML_database
  dataset_directory: TestTrackML
  time_resolution: 4
  max_tracks: 6
  mean_events: 10
  n_samples: 300
  log_label: ML10_DeltaT4


model:
  encoder:
    hidden_linear_layers:
    - 128
    - 128
    - 64
    out_linear_layer: 32
    n_convolutions: 6
  classifier:
    edge_weight_layers:
    - 128
    - 128
    edge_update_layers:
    - 128
    - 128
    node_update_layers:
    - 128
    - 128
    n_convolutions: 6

training:
  pos_weight: 1
  neg_weight: 0.9
  gamma: 1.5
  save_prob: 1
  n_epochs: 10

loader:
  load_model: True
  model_dirrectory: path_to_the_directory_containing_the_folder_"models"_with_saved_model
  model_name: model's_name

saver:
  model_name: Test_model
  save_step: 5

